### ISSUE TITLE
Uncaught Error: Class 'predictionio\EventClient' not found

### ISSUE THREAD

**Issue by rathodsunny005** [richdynamix/personalised-products#26]
Hello,
When I try to install extension I got following error.
```
PHP Fatal error:  Uncaught Error: Class 'predictionio\EventClient' not found in /opt/bitnami/apps/magento/htdocs/app/code/Richdynamix/PersonalisedProducts/Model/PredictionIO/Factory.php:28
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/app/code/Richdynamix/PersonalisedProducts/Model/PredictionIO/EventClient/Client.php(69): Richdynamix\PersonalisedProducts\Model\PredictionIO\Factory->create('event', 'http::', NULL)
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Richdynamix\PersonalisedProducts\Model\PredictionIO\EventClient\Client->__construct(Object(Richdynamix\PersonalisedProducts\Model\PredictionIO\Factory), Object(Richdynamix\PersonalisedProducts\Logger\PersonalisedProductsLogger), Object(Richdynamix\PersonalisedProducts\Helper\Config), Object(Richdynamix\PersonalisedProducts\Helper\Urls))
#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createOb in /opt/bitnami/apps/magento/htdocs/app/code/Richdynamix/PersonalisedProducts/Model/PredictionIO/Factory.php on line 28
```
Can you please help on this ?
Thanks

**Comment by gofornaman** [comment]
Hi, did you install predictionio on linux or windows?

**Comment by rathodsunny005** [comment]
I have installed In Linux, I have separate server for prediction.io

**Comment by atsareva** [comment]
Hi! You should run the next command in the magento root directory
`composer require predictionio/predictionio`
and then recompile magento again.
